// Generated by CoffeeScript 1.3.3
$(function() {
  var qry1, qry2, qry3;

  $('.dimensions').html('Width: ' + $(window).width() + 'px');

  $(window).resize(function() {
    return $('.dimensions').html('Width: ' + $(this).width() + 'px');
  });

  //Header phone number movement
  MovePhoneNumber = {
    Mobile: function() {
      var clone = $('.contact-phone').clone();
      $('.contact-phone').hide();
      $('.header-logo').append(clone);
    },
    Destroy: function() {
      $('.header-logo .contact-phone').remove();
      $('.contact-phone').show();
    }
  },
  //Header dealer location movement
  MoveHeaderPhoneLocation = {
    Mobile: function() {
      var clone = $('.contact-phone').clone();
      $('.contact-phone').hide();
      $('.header-contact').hide();
      $('.navbar-default .navbar-header').append(clone);      
    },
    Destroy: function() {
      $('.navbar-default .navbar-header .contact-phone').remove();
      $('.contact-phone').show(); 
      $('.header-contact').show();     
    }
  },
  //Product listing product buttons movement
  MoveProductListingButtons = {
    Mobile: function() {
      if ($('body').hasClass('page-template-page-product-listing')) {
        $( '.product' ).each(function() {
          var clone = $(this).find('.text-center').clone().addClass('product-button');
          $(this).find('.text-center').hide();
          $(this).append(clone); 
        });       
      }    
    },
    Destroy: function() {
      if ($('body').hasClass('page-template-page-product-listing')) {
        $( '.product' ).each(function() {
          $('.product-button').remove();
          $(this).find('.text-center').show();
        });
      }
    }
  }

  qry1 = Harvey.attach('(min-width: 992px)', {
    setup: function() {
      //return console.log('SETUP', this.condition);
    },
    on: function() {
      //console.log("Hello Desktop");
      //return console.log('ON', this.condition);
      MoveHeaderPhoneLocation.Destroy();
      MovePhoneNumber.Destroy();
    },
    off: function() {
      //return console.log('OFF', this.condition);
    }
  });
  //Tablet
  qry2 = Harvey.attach('(max-width: 991px) and (min-width: 769px)', {
    setup: function() {
      //return console.log('SETUP', this.condition);
    },
    on: function() {
      MovePhoneNumber.Destroy();
      MoveHeaderPhoneLocation.Destroy();
      MoveHeaderPhoneLocation.Mobile();
      MoveProductListingButtons.Destroy();
      //return console.log('ON', this.condition);
    },
    off: function() {
      //return console.log('OFF', this.condition);
    }
  });
  //Mobile down
  qry3 = Harvey.attach('(max-width: 768px)', {
    setup: function() {
      //return console.log('SETUP', this.condition);
    },
    on: function() {
      MovePhoneNumber.Mobile();
      MoveProductListingButtons.Mobile();  
      MoveHeaderPhoneLocation.Mobile();
      //return console.log('ON', this.condition);
    },
    off: function() {
      //return console.log('OFF', this.condition);
    }
  });

});